# Generated by Django 3.0.1 on 2020-07-01 18:21

import birds.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/default_profile_pic.jpg', upload_to='profile_pics', validators=[birds.utils.file_size]),
        ),
    ]
