# Generated by Django 3.0.1 on 2020-07-01 18:18

import birds.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20200629_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
        migrations.AlterField(
            model_name='bird',
            name='picture',
            field=models.ImageField(upload_to='bird', validators=[birds.utils.file_size]),
        ),
    ]
