# Generated by Django 3.0.1 on 2020-07-01 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birds', '0004_auto_20200701_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeded', models.BooleanField(default=False)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='birds.Bird')),
                ('seeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
